/*
 * usb_hid_consumer.h
 *
 * Created: 26-Nov-18 2:38:56 PM
 *  Author: Vlad
 */ 


#ifndef USB_HID_CONSUMER_H_
#define USB_HID_CONSUMER_H_


#define HID_CONSUMER_CHANNEL_UP		0x9C
#define HID_CONSUMER_CHANNEL_DOWN	0x9D
#define HID_CONSUMER_VOLUME_UP		0xE9
#define HID_CONSUMER_VOLUME_DOWN	0xEA
#define HID_CONSUMER_MUTE			0xE2
#define HID_CONSUMER_POWER			0x30
#define HID_CONSUMER_RECALL_LAST	0x83
#define HID_CONSUMER_ASSIGN_SEL		0x81
#define HID_CONSUMER_PLAY			0xB0
#define HID_CONSUMER_PAUSE			0xB1
#define HID_CONSUMER_RECORD			0xB2
#define HID_CONSUMER_FAST_FORWARD	0xB3
#define HID_CONSUMER_REWIND			0xB4
#define HID_CONSUMER_SCAN_NEXT_TRK	0xB5
#define HID_CONSUMER_SCAN_PREV_TRK	0xB6
#define HID_CONSUMER_STOP			0xB7



#endif /* USB_HID_CONSUMER_H_ */